# Generated by Django 5.0.7 on 2024-07-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=100)),
                ('organisation_type', models.CharField(max_length=100)),
                ('organisation_name', models.CharField(max_length=100)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('contest_visibility', models.CharField(max_length=50)),
                ('participant_limit', models.IntegerField(blank=True, null=True)),
                ('contest_image', models.ImageField(blank=True, null=True, upload_to='contest_images/')),
            ],
        ),
    ]
