# Generated by Django 5.0.7 on 2024-12-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestproblems',
            unique_together={('contest', 'problem')},
        ),
    ]
