# Generated by Django 5.0.7 on 2024-10-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestdetails',
            name='contest_banner_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contestdetails',
            name='contest_default_banner_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
