# Generated by Django 5.0.7 on 2024-10-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='time_taken',
            field=models.DurationField(),
        ),
        migrations.AlterModelTable(
            name='ranking',
            table='ranking',
        ),
        migrations.DeleteModel(
            name='Samples',
        ),
    ]
