# Generated by Django 5.0.7 on 2024-07-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='contest_image',
        ),
    ]
