# Generated by Django 5.0.7 on 2024-10-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0002_alter_ranking_time_taken_alter_ranking_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ranking',
            table='rankings',
        ),
    ]
