# Generated by Django 5.0.7 on 2024-10-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0002_remove_users_login_password_alter_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
