# Generated by Django 5.0.7 on 2024-10-02 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0003_alter_ranking_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='time_taken',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField()),
                ('sample_order', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding_contest_app.problems')),
            ],
            options={
                'verbose_name': 'Sample Input/Output',
                'db_table': 'sample_input_output',
            },
        ),
    ]
