# Generated by Django 5.0.7 on 2024-10-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0004_alter_ranking_time_taken_samples'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ranking',
            table='ranking',
        ),
    ]
