# Generated by Django 4.2.13 on 2024-07-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0004_remove_contests_contest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='contest_image',
            field=models.ImageField(blank=True, null=True, upload_to='contest_images/'),
        ),
    ]
