# Generated by Django 5.0.7 on 2024-10-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0005_alter_ranking_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samples',
            options={},
        ),
        migrations.AlterModelTable(
            name='samples',
            table=None,
        ),
    ]
