# Generated by Django 4.2.13 on 2024-07-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0005_contests_contest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='contest_image',
        ),
    ]
