# Generated by Django 5.0.7 on 2024-10-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0006_alter_samples_options_alter_samples_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samples',
            options={'verbose_name': 'Sample Input/Output'},
        ),
        migrations.AlterModelTable(
            name='samples',
            table='sample_input_output',
        ),
    ]
