# Generated by Django 5.0.7 on 2024-07-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_contest_app', '0007_contests_contest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='contest_image',
            field=models.ImageField(blank=True, null=True, upload_to='coding-images'),
        ),
    ]
